In [1]:
import numpy as np
import torch

In [2]:
torch.tensor([[1,2], [3, 4.]])

tensor([[1., 2.],
        [3., 4.]])

In [3]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
torch.zeros(3,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [5]:
t = torch.randn(3,5)
t

tensor([[-0.4373, -0.6768, -0.4706, -0.3843, -0.8217],
        [ 0.9641, -0.1005, -0.0542, -0.3754, -1.2571],
        [ 0.6117, -1.3401, -0.1596, -0.9439, -0.7761]])

In [6]:
t.size()

torch.Size([3, 5])

In [7]:
x = t.numpy()
x

array([[-0.43731886, -0.67684007, -0.47064334, -0.3843267 , -0.82166046],
       [ 0.9640504 , -0.10052977, -0.05422737, -0.37544295, -1.2571412 ],
       [ 0.6116663 , -1.3401384 , -0.15962887, -0.94388986, -0.77607745]],
      dtype=float32)

In [8]:
t = torch.tensor([[1,2,3], [4, 5, 6.]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
t[0, 2]

tensor(3.)

In [10]:
t[:, :2]

tensor([[1., 2.],
        [4., 5.]])

In [11]:
t[:, [1,2]]

tensor([[2., 3.],
        [5., 6.]])

In [12]:
t[t > 3]

tensor([4., 5., 6.])

In [13]:
t[0, 1] = 100
t

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])

In [14]:
t[:, 1] = 200
t

tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])

In [15]:
t[t > 10] = 20
t

tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])

---

In [16]:
t = torch.tensor([[1,2,3], [4, 5, 6.]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
m = torch.mean(t)
m

tensor(3.5000)

In [18]:
m = t.mean()
m

tensor(3.5000)

In [19]:
m_value = m.item()
m_value

3.5

In [20]:
m2 = t.mean(0)
m2

tensor([2.5000, 3.5000, 4.5000])

In [21]:
t.view(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [22]:
t.view(1,-1)

tensor([[1., 2., 3., 4., 5., 6.]])

In [23]:
t.t()

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [24]:
torch.cat([t, t], dim=0)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.]])

In [25]:
torch.cat([t, t], dim=1)

tensor([[1., 2., 3., 1., 2., 3.],
        [4., 5., 6., 4., 5., 6.]])

In [26]:
torch.svd(t)

(tensor([[-0.3863, -0.9224],
         [-0.9224,  0.3863]]),
 tensor([9.5080, 0.7729]),
 tensor([[-0.4287,  0.8060],
         [-0.5663,  0.1124],
         [-0.7039, -0.5812]]))